locale: en-US
title: Eric's blog
description: A blog with stuff important to me
url: http://ebailey78.github.io
logo: "/images/so-simple-site-logo.png"
date_format: "%B %-d, %Y"
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
theme: jekyll-theme-midnight

liquid:
  error_mode: strict

markdown: kramdown

paginate: 10
paginate_path: /page:num/

search_full_content: true

category_archive_path: "/categores/#"
tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: false
      share: true
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

author:
  name: Eric Bailey
  email: idemrisc@gmail.com
